# Copyright © 2015-2016 Collabora Ltd.
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation files
# (the "Software"), to deal in the Software without restriction,
# including without limitation the rights to use, copy, modify, merge,
# publish, distribute, sublicense, and/or sell copies of the Software,
# and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
# BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
# ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

sudo: required
dist: xenial
language: c
script:
  - ./tools/ci-install.sh
  - ci_parallel=2 ci_sudo=yes ./tools/ci-build.sh

env:
  - ci_variant=production
  - ci_variant=debug
  - ci_variant=reduced
  - ci_variant=legacy
  - ci_buildsys=cmake-dist
  - ci_host=i686-w64-mingw32
  - ci_host=i686-w64-mingw32 ci_buildsys=cmake ci_variant=debug
  - ci_host=x86_64-w64-mingw32 ci_variant=debug
  - ci_host=x86_64-w64-mingw32 ci_buildsys=cmake
  - ci_docker=debian:stretch-slim ci_distro=debian ci_suite=stretch
  - ci_docker=debian:buster-slim ci_distro=debian ci_suite=buster

# vim:set sw=2 sts=2 et:
